# Generated by Django 4.1.1 on 2023-03-13 13:29

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mebel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=41, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('addres', models.CharField(max_length=100)),
                ('narx', models.PositiveIntegerField()),
                ('chegirma', models.PositiveIntegerField(default=0)),
                ('like', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('razmer', models.CharField(help_text="bo'yi,eni,qalinligi", max_length=112)),
                ('body', models.TextField()),
                ('turi', models.CharField(choices=[('kuxni', 'Kuxni'), ('mehmonxona', 'Mehmonxona'), ('devan', 'Devan'), ('shkaf', 'Shkaf'), ('bolalar', 'Bolalar'), ('romlar', 'Romlar')], default='kuxni', max_length=31)),
                ('rangi', models.CharField(help_text='masalan: oq,qora,qizil,sariq', max_length=41)),
                ('photo', models.ImageField(upload_to='rasm')),
                ('status', models.CharField(choices=[('active', 'Activ'), ('deactiv', 'Deactiv')], default='active', max_length=31)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updatead', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Uy jihozi',
                'verbose_name_plural': 'Uy jihozlari',
                'ordering': ('-created_at', 'status'),
            },
        ),
        migrations.CreateModel(
            name='Savat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdori', models.PositiveIntegerField(default=0)),
                ('summa', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Activ'), ('deactiv', 'Deactiv')], default='active', max_length=31)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updatead', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mebel.mebel')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sinov')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Yaratilgan vaqti')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagine', to='mebel.mebel')),
            ],
        ),
    ]
